### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by WikiaLuke** [Wikia/style-guide#30]
![favicon](https://cloud.githubusercontent.com/assets/8378211/6287013/e8366aec-b90d-11e4-8cc7-c8cef2cba1fa.png)
ico file: 
https://wikia.box.com/s/r4scrjep5pq0rt4karvc0sp5sgoiluhl

**Comment by mklucsarits** [comment]
The favicon will be added with these changes:
https://github.com/Wikia/style-guide/pull/35
