### ISSUE TITLE
Fix up dropdown-icon web component to be used in more places

### ISSUE THREAD

**Issue by lizlux** [Wikia/style-guide#44]
In https://github.com/Wikia/style-guide/pull/42 I converted the global-nav's dropdown menu into a web component, but it's very basic and is not in a place where it can be applied to dropdown menus globally. This ticket is to basically finish this task. Some possible action items are: 
- Split it up into two components: icon itself and the dropdown menu
- Add more configurability to the components such as class names, values for `data-offset-x` and `data-offset-y`
- Apply new web components to the two examples in the "Forms and Dropdowns" page
- Rename the class `f-dropdown` to something like `dropdown-menu`
- Fix this in IE10. Works fine in IE11.

**Comment by WikiaLuke** [comment]
I'm not sure if we gonna need this component anymore, please ask Kyle/James for more info.
